#!/usr/bin/env zsh

orig_cwd="$(pwd)"

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)
[[ -f /opt/dev/sh/chruby/chruby.sh ]] && { type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; } }
[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

cd ~/src/github.com/Shopify/roast
ROAST_WORKING_DIRECTORY="$orig_cwd" bin/roast $@